home:
    pattern:  /home/
    defaults: { _controller: RezoRezoSupBundle:Default:index }

thanks:
    pattern:  /thanks/
    defaults: { _controller: RezoRezoSupBundle:Default:thanks }

charte:
    pattern:  /charte/
    defaults: { _controller: RezoRezoSupBundle:Default:charte }


news:
    pattern:  /actus/
    defaults: { _controller: RezoRezoSupBundle:Default:news , page:1}


news_page:
    pattern:  /actus/{page}/
    defaults: { _controller: RezoRezoSupBundle:Default:news }
    requirements:
        page: \d+

news_post_process:
    pattern:  /post/
    defaults: { _controller: RezoRezoSupBundle:Default:newsPostProcess }
    requirements:
        _method : POST

news_post:
    pattern:  /post/
    defaults: { _controller: RezoRezoSupBundle:Default:newsPost }


    
