home:
    pattern: /  
    defaults: { _controller: RezoRezoSupBundle:Default:index }

thanks:
    pattern:  /thanks/
    defaults: { _controller: RezoRezoSupBundle:Default:thanks }

charte:
    pattern:  /charte/
    defaults: { _controller: RezoRezoSupBundle:Default:charte }


news:
    pattern:  /actus/
    defaults: { _controller: RezoRezoSupBundle:Default:news , page:1}


news_page:
    pattern:  /actus/{page}/
    defaults: { _controller: RezoRezoSupBundle:Default:news }
    requirements:
        page: \d+



news_post_process:
    pattern:  /post/{newsId}/
    defaults: { _controller: RezoRezoSupBundle:Administration:newsPostProcess}
    requirements:
        _method : POST

news_post:
    pattern:  /post/
    defaults: { _controller: RezoRezoSupBundle:Administration:newsPostProcess, newsId:-1}

servers:
    pattern:  /servers/
    defaults: { _controller: RezoRezoSupBundle:Default:servers }

map:
    pattern: /map/
    defaults: { _controller: RezoRezoSupBundle:Default:map }

sessions:
    pattern: /sessions/
    defaults: { _controller: RezoRezoSupBundle:Default:sessions }

proxy:
    pattern: /proxy/
    defaults: { _controller: RezoRezoSupBundle:Default:proxy }

faq:
    pattern: /faq/
    defaults: { _controller: RezoRezoSupBundle:Default:faq }

services:
    pattern: /services/
    defaults: { _controller: RezoRezoSupBundle:Default:services }


commandes:
    pattern: /commandes/
    defaults: { _controller: RezoRezoSupBundle:Default:commandes }

annuaire:
    pattern: /annuaire/
    defaults: { _controller: RezoRezoSupBundle:Default:annuaire }

listeAnnuaireUser:
    pattern: /annuaire/liste/{username}//{operateur}
    defaults: { _controller: RezoRezoSupBundle:Ajax:liste, server_id:-1 }

listeAnnuaireFull:
    pattern: /annuaire/liste/{username}/{server_id}/{operateur}
    defaults: { _controller: RezoRezoSupBundle:Ajax:liste }

listeAnnuaireEmpty:
    pattern: /annuaire/liste///{operateur}
    defaults: { _controller: RezoRezoSupBundle:Ajax:liste, server_id:-1, username:%}

listeAnnuaireServer:
    pattern: /annuaire/liste//{server_id}/{operateur}
    defaults: { _controller: RezoRezoSupBundle:Ajax:liste, username:%}


connexion:
    pattern: /loginf
    defaults: { _controller: RezoRezoSupBundle:Default:login}

redirect:
    pattern: /redirect
    defaults: { _controller: RezoRezoSupBundle:Default:redirect}
    
deleteNews:
    pattern: /delete/{newsId}
    defaults: { _controller: RezoRezoSupBundle:Administration:delete}
    
editNews:
    pattern: /edit/{newsId}
    defaults: { _controller: RezoRezoSupBundle:Administration:newsPostProcess}
    
administration:
    pattern: /admin/
    defaults: { _controller:RezoRezoSupBundle:Administration:index}

newsAdministration:
    pattern: /admin/news/
    defaults: { _controller:RezoRezoSupBundle:Administration:news, page:1}

newsAdministration_page:
    pattern:  /admin/actus/{page}/
    defaults: { _controller: RezoRezoSupBundle:Administration:news }
    requirements:
        page: \d+
        
mailingAdministration:
    pattern:   /admin/mailing/
    defaults: { _controller:RezoRezoSupBundle:Administration:mailing}
    
changeAccess:
    pattern:   /admin/mailing/set/{id}/{level}
    defaults: { _controller:RezoRezoSupBundle:Ajax:changeAccess}

delAdmin:
    pattern:   /admin/mailing/del/{id}
    defaults: { _controller:RezoRezoSupBundle:Ajax:delAdmin}

getAdmin:
    pattern:   /admin/mailing/get/{id}
    defaults: { _controller:RezoRezoSupBundle:Ajax:getAdmin}



createAlias:
    pattern:   /admin/mailing/create/
    defaults:  { _controller:RezoRezoSupBundle:Ajax:createAlias}
    requirements:
        _method : POST
        
createAdmin:
    pattern:   /admin/mailing/createAdmin/
    defaults:  { _controller:RezoRezoSupBundle:Administration:createAdmin}
    requirements:
        _method : POST        
        
changePass:
    pattern:   /admin/mailing/change/
    defaults:  { _controller:RezoRezoSupBundle:Administration:changePass}
    requirements:
        _method : POST        

updateMail:
    pattern:   /admin/mailing/update/
    defaults:  { _controller:RezoRezoSupBundle:Ajax:updateMail}
