parameters:
#    rezo_rezo_sup.example.class: Rezo\RezoSupBundle\Example

services:
#    rezo_rezo_sup.example:
#        class: %rezo_rezo_sup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
